image: node:12

definitions:
  install: &install
    step:
      name: Install Dependencies
      script:
        - npm ci
      artifacts:
        - node_modules/**

  test:lint: &test-lint
    step:
      name: Verify lint errors
      script:
        - npm run test:lint

  test:build: &test-build
    step:
      name: Verify build errors
      script:
        - npm run build


  deploy:test: &deploy-test
    step:
      name: Deploy to s3 test environment
      deployment: TEST
      script:
        - npm run build
        - pipe: atlassian/aws-s3-deploy:1.1.0
          variables:
            AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET
            LOCAL_PATH: build
            DELETE_FLAG: 'true'

  deploy:production: &deploy-production
    step:
      name: Deploy to s3 production environment
      deployment: PRODUCTION
      script:
        - npm run build
        - pipe: atlassian/aws-s3-deploy:1.1.0
          variables:
            AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET
            LOCAL_PATH: build
            DELETE_FLAG: 'true'

pipelines:
  pull-requests:
    PIZ-*:
      - <<: *install
      - parallel:
          - <<: *test-lint
          - <<: *test-build
  branches:
    # Deploy to test env
    dev:
      - <<: *install
      - <<: *test-lint
      - <<: *deploy-test
    # Deploy to production env
    master:
      - <<: *install
      - <<: *test-lint
      - <<: *deploy-production